places=["Karachi","Hyderabad","Islamabad","Lahore","Balakot"]
print("Original List:")
print(places)
print("Sorted List:")
print(sorted(places))
print("Original List:")
print(places)
print("Reverse List:")
print(sorted(places,reverse=True))
print("Original List:")
print(places)
places.reverse()
print("Reverse List using reverse():")
print(places)
print("Using reverse() to go back to original list:")
places.reverse()
print(places)
places.sort()
print("Sorted List using sort():")
print(places)
places.sort(reverse=True)
print("Reverse alphabetical order using sort()")
print(places)